/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "uart_pc.h"
#include "isr_uart_pc_rx.h"
#include "pump_timer_clock_1.h"
#include "pump_timer_1.h"
#include "pump_timer_clock_3.h"
#include "isr_pump_timer_2.h"
#include "pump_timer_clock_2.h"
#include "pump_timer_2.h"
#include "isr_pump_timer_1.h"
#include "pump_timer_3.h"
#include "isr_pump_timer_3.h"
#include "check_weight_timer_clock.h"
#include "check_weight_timer.h"
#include "isr_check_weight_timer.h"
#include "weight_adc.h"
#include "weight_selector.h"
#include "weight_1_aliases.h"
#include "weight_1.h"
#include "weight_2_aliases.h"
#include "weight_2.h"
#include "weight_3_aliases.h"
#include "weight_3.h"
#include "gpio_pump_1_aliases.h"
#include "gpio_pump_1.h"
#include "gpio_pump_3_aliases.h"
#include "gpio_pump_3.h"
#include "gpio_pump_2_aliases.h"
#include "gpio_pump_2.h"
#include "uart_rpi.h"
#include "isr_uart_rpi_rx.h"
#include "uart_pc_IntClock.h"
#include "weight_adc_IRQ.h"
#include "weight_adc_theACLK.h"
#include "weight_adc_ExtVref_aliases.h"
#include "weight_adc_ExtVref.h"
#include "uart_rpi_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

