#ifndef DMC_NETLINK_ATTR_H
#define DMC_NETLINK_ATTR_H

/* ################################# */
/*    Defining netlink attributes    */
/*       for netlink messages        */
/* ################################# */

#define DMC_EVENT_GENL_BASE_ATTR_TYPE 1
#define __DMC_EVENT_GENL_BASE_ATTR_MAX 1

enum dmc_event_nl_container_weight_measured_attr
{
  DMC_EVENT_GENL_CONTAINER_WEIGHT_MEASURED_ATTR_UNSPECIFIED = 0,
  DMC_EVENT_GENL_CONTAINER_WEIGHT_MEASURED_ATTR_TYPE =
      DMC_EVENT_GENL_BASE_ATTR_TYPE,
  DMC_EVENT_GENL_CONTAINER_WEIGHT_MEASURED_ATTR_CONTAINER = 2,
  DMC_EVENT_GENL_CONTAINER_WEIGHT_MEASURED_ATTR_WEIGHT    = 3,
  __DMC_EVENT_GENL_CONTAINER_WEIGHT_MEASURED_ATTR_MAX,
};

enum dmc_event_nl_out_of_order_attr
{
  DMC_EVENT_GENL_OUT_OF_ORDER_ATTR_UNSPECIFIED = 0,
  DMC_EVENT_GENL_OUT_OF_ORDER_ATTR_TYPE        = DMC_EVENT_GENL_BASE_ATTR_TYPE,
  DMC_EVENT_GENL_OUT_OF_ORDER_ATTR_MESSAGE     = 2,
  DMC_EVENT_GENL_OUT_OF_ORDER_ATTR_REASON      = 3,
  __DMC_EVENT_GENL_OUT_OF_ORDER_ATTR_MAX,
};

enum dmc_event_nl_user_confirm_attr
{
  DMC_EVENT_GENL_USER_CONFIRM_ATTR_UNSPECIFIED = 0,
  DMC_EVENT_GENL_USER_CONFIRM_ATTR_TYPE        = DMC_EVENT_GENL_BASE_ATTR_TYPE,
  __DMC_EVENT_GENL_USER_CONFIRM_ATTR_MAX,
};

enum dmc_event_nl_fluid_pour_requested_attr
{
  DMC_EVENT_GENL_FLUID_POUR_REQUESTED_ATTR_UNSPECIFIED = 0,
  DMC_EVENT_GENL_FLUID_POUR_REQUESTED_ATTR_TYPE = DMC_EVENT_GENL_BASE_ATTR_TYPE,
  DMC_EVENT_GENL_FLUID_POUR_REQUESTED_ATTR_CONTAINER = 2,
  DMC_EVENT_GENL_FLUID_POUR_REQUESTED_ATTR_AMOUNT    = 3,
  __DMC_EVENT_GENL_FLUID_POUR_REQUESTED_ATTR_MAX,
};

#endif /* DMC_NETLINK_ATTR_H */